"""empty message

Revision ID: 05c044750bc1
Revises: e5c0497f6f14
Create Date: 2018-11-28 16:52:11.065000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c044750bc1'
down_revision = 'e5c0497f6f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_description')
    # ### end Alembic commands ###
